// Generated by CoffeeScript 1.4.0
(function() {
  var sandbox;

  sandbox = {};

  if (typeof window !== "undefined" && window !== null) {
    window.sandbox = sandbox;
  }

  if (typeof module !== "undefined" && module !== null) {
    module.exports = sandbox;
  }

}).call(this);
