// Generated by CoffeeScript 1.4.0
(function() {

  describe('sandbox', function() {
    it('Exists', function() {
      return expect(sandbox).to.exist;
    });
    it('HTML', function() {
      var el;
      el = sandbox({
        html: '<p>test</p>'
      });
      return expect($(el.contentDocument.body).find('p').text()).to.be('test');
    });
    it('CSS', function() {
      var el;
      el = sandbox({
        css: 'body { background-color: rgb(50, 50, 50); }',
        html: '<p>test</p>'
      });
      return expect($(el.contentDocument.body).css('background-color')).to.be('rgb(50, 50, 50)');
    });
    it('Access global variables inside frame', function() {
      var el;
      el = sandbox({
        html: '<p>testing yay</p>',
        js: 'window.yay = 5'
      });
      return expect(el.contentWindow.yay).to.be(5);
    });
    it('executes parent js', function(async) {
      var el;
      window.jsCallback = async;
      return el = sandbox({
        html: '<p>test</p>',
        js: 'parent.jsCallback()'
      });
    });
    it('harnesses alerts', function() {
      var annoying, dialogs, noDialogs, _i, _len, _ref, _results;
      noDialogs = sandbox({
        dialogs: false
      });
      dialogs = sandbox({
        dialogs: true
      });
      _ref = ['alert', 'prompt', 'confirm'];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        annoying = _ref[_i];
        expect(noDialogs.contentWindow[annoying].toString()).to.be('function () {}');
        _results.push(expect(dialogs.contentWindow[annoying].toString()).to.not.be('function () {}'));
      }
      return _results;
    });
    return it('appends to el', function() {
      var el;
      el = $('div').appendTo('body');
      sandbox({
        html: '<p>test</p>',
        el: el
      });
      return expect(el.find('iframe').length).to.be(1);
    });
  });

}).call(this);
